source "https://cdn.cocoapods.org/"

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SimpleShoppingMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleShoppingMall
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'YYModel'

  target 'SimpleShoppingMallTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Kiwi'
    pod 'Quick'
  end

  target 'SimpleShoppingMallUITests' do
    # Pods for testing
  end

end
